name: Update Stats

on:
  schedule:
    - cron: "0 */6 * * *"   # every 6 hours
  workflow_dispatch:        # manual trigger

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install requests

      - name: Run script
        run: python update_stats.py

      - name: Commit and Push changes
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "actions@github.com"
          git add stats.json
          git commit -m "Update stats" || echo "No changes to commit"
          git push
